spring:
  application:
    name: rate-limiter
  redis:
    database: 0
    host: 192.168.124.10 # your ip
    port: 6379 # your port
    password: redis # your redis password

server:
  port: 10800
logging:
  file: log/${spring.application.name}.log