---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Chanmoey.
--- DateTime: 2022/4/12 10:59
---

local key = KEYS[1]

local limit = tonumber(ARGV[1])

local count = tonumber(redis.call('get', key) or "0")

if count + 1 > limit then
    return false
else
    redis.call("INCRBY", key, 1)
    redis.call("EXPIRE", key, 1)
    return true
end